[pytest]

addopts =
    -v
    -s
    --tb=short
    --alluredir=allure-results

testpaths =
    tests

python_files =
    test_*.py

python_functions =
    test_*

#markers =
    #smoke: Smoke Tests
    #regression: Regression Tests
    #api: API Tests
